def get_architectures():
    return [
        {
            "name": "GPT",
            "model_family": "GPT-like",
            "architecture": "Decoder-only",
            "training_objective": "Next-token prediction",
            "input_output_format": "Plain text → next token",
            "generation": "Autoregressive token-by-token generation",
            "best_for": ["Chatbots", "Story writing", "Code generation"],
            "bad_for": ["Translation", "Strict formatting tasks"],
            "generation_style": "Creative",
            "open_source": False,
            "inference_cost": "High",
            "context_window": 8192,
        },
        {
            "name": "Claude",
            "model_family": "GPT-like",
            "architecture": "Decoder-only",
            "training_objective": "Next-token prediction + safety tuning",
            "input_output_format": "Plain text → next token",
            "generation": "Autoregressive with long-context optimization",
            "best_for": ["Long document analysis", "Safe conversational AI"],
            "bad_for": ["Low-latency tasks"],
            "generation_style": "Balanced",
            "open_source": False,
            "inference_cost": "High",
            "context_window": 100000,
        },
        {
            "name": "Gemini",
            "model_family": "GPT-like (Multimodal)",
            "architecture": "Decoder-only",
            "training_objective": "Multimodal next-token prediction",
            "input_output_format": "Text / Image / Audio → token prediction",
            "generation": "Token prediction across multiple modalities",
            "best_for": ["Multimodal reasoning", "Vision + text tasks"],
            "bad_for": ["Open-source customization"],
            "generation_style": "Balanced",
            "open_source": False,
            "inference_cost": "High",
            "context_window": 32000,
        },
        {
            "name": "LLaMA",
            "model_family": "GPT-like",
            "architecture": "Decoder-only",
            "training_objective": "Next-token prediction",
            "input_output_format": "Plain text → next token",
            "generation": "Efficient autoregressive transformer",
            "best_for": ["Local LLMs", "Research", "Fine-tuning"],
            "bad_for": ["Out-of-the-box chat quality"],
            "generation_style": "Balanced",
            "open_source": True,
            "inference_cost": "Low",
            "context_window": 8192,
        },
        {
            "name": "T5 / FLAN-T5",
            "model_family": "T5-like",
            "architecture": "Encoder–Decoder",
            "training_objective": "Sequence-to-sequence denoising",
            "input_output_format": "Task-prefixed text → structured output",
            "generation": "Encodes entire input then decodes output",
            "best_for": ["Translation", "Summarization", "Question Answering"],
            "bad_for": ["Open-ended chat"],
            "generation_style": "Deterministic",
            "open_source": True,
            "inference_cost": "Low",
            "context_window": 4096,
        }
    ]
